site_name: Marketingmethoden
site_url: https://mydomain.org/mysite
theme:
name: material
language: de
features:
- navigation.tracking
- navigation.sections
- navigation.expand
- navigation.path
- toc.integrate
- navigation.top
- search.suggest

nav:
- Administratives: admin.md
- Grundlagen: 
  - Statistik: Grundlagen/grundlagenstatistik.md
  - empirisches Arbeiten: Grundlagen/grundlagenempirischesarbeiten.md
- experimentelles Design:
  - experimentelles Design: experimentellesdesign/experimentellesdesign.md
  - einfaktorielles Design: experimentellesdesign/einfaktoriellesdesign.md
  - zweifaktorielles Design: experimentellesdesign/zweifaktoriellesdesign.md
- Analysemodelle: 
  - Regression: Analysemodelle/regression.md
  - Varianzanalyse: Analysemodelle/varianzanalyse.md
  - Mediation: Analysemodelle/mediation.md
  - Moderation: Analysemodelle/moderation.md

extra_css:
  - stylesheets/extra.css