site_name: My Docs
site_url: https://mydomain.org/mysite
theme:
name: material
features:
- navigation.instant
- navigation.instant.progress
- navigation.instant.preview
- navigation.tracking
- navigation.tabs
- navigation.tabs.sticky
- navigation.sections
- navigation.expand
- toc.integrate
- navigation.top
- search.suggest

nav:
- Home: wilkommen.md
- Introduction: index.md
- Grundlagen: 
  - Statistik: grundlagen/grundlagenstatistik.md
  - empirisches Arbeiten: grundlagen/grundlagenempirischesarbeiten.md
  - experimentelles Design: experimentellesdesign.md

